### ISSUE TITLE
Add trivago 

### ISSUE THREAD

**Issue by Mhmdabed11** [shubheksha/companies-sponsoring-visas#9]
Trivago offers relocation for its talents. It is located in Dusseldorf, Germany. It also offers a relocation package as well!

Name: Trivago
Location: Dusseldorf, Germany
Roles Sponsored: Software Engineering, Media and Marketing, Analytics, People
Careers Page: https://company.trivago.com/open-positions/
Relocation Bonus? : yes

**Comment by shubheksha** [comment]
Thank you! 👍
